// components/process/process.js
Component({
  properties:{
    stateCode:{
      type:Array,
      value:[]
    }
  },
  /**
   * 页面的初始数据
   */
  
  data: {
    state:[
      [],
      [
        {
          name:"收集中",
          button:[[],[]],
          states:['未提交','已提交']
        },
        {
          name:"审核中",
          button:[[],[]],
          states:['正在审核','已通过']
        }
      ],
      [
        {
          name:"面试通知",
          button:[['参加','缺席'],[],[]],
          states:['待确认','确认参加','确认缺席']
        },
        {
          name:"面试签到",
          button:[['签到'],[]],
          states:['待签到','已签到']
        },
        {
          name:"面试叫号",
          button:[[]],
          states:['等待叫号']
        },
        {
          name:"面试中",
          button:[[]],
          states:['面试中']
        },
        {
          name:"面试结束",
          button:[[]],
          states:['已结束']
        }
      ],
      [
        {
          name:"笔试通知",
          button:[['参加','缺席'],[],[]],
          states:['待确认','确认参加','确认缺席']
        },
        {
          name:"笔试签到",
          button:[['签到'],[]],
          states:['待签到','已签到']
        },
        {
          name:"笔试交卷",
          button:[['交卷'],[]],
          states:['未交卷','已交卷']
        }
      ],
      [
        {
          name:"等待叫号",
          button:[[]],
          states:['等待叫号']
        },
        {
          name:"第二志愿",
          button:[[]],
          states:['等待面试']
        }
      ],
      [
        {
          name:"录取结果",
          button:[[]],
          states:['','已录用','未录用']
        }
      ]
    ],
    height:[0,300,550,400,300,200],
    status:['123','报名','一轮面试','笔试','二轮面试','结果']
  },

  /**
   * 生命周期函数--监听页面加载
   */
  methods:{

  }
})